'use strict';function w(f,a,b,d){f.u.Eb(f.eb,a,b,d,void 0)}function H(f,a,b,d){f.u.da?w(f,a,b,d):f.u.zf()._OnMessageFromDOM({type:"event",component:f.eb,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function J(f,a,b){f.u.C(f.eb,a,b)}function L(f,a){for(const [b,d]of a)J(f,b,d)}function M(f){f.Ub||(f.u.hf(f.qe),f.Ub=!0)}window.Ua=class{constructor(f,a){this.u=f;this.eb=a;this.Ub=!1;this.qe=()=>this.Ea()}pd(){}Ea(){}};function N(f){-1!==f.Sa&&(self.clearTimeout(f.Sa),f.Sa=-1)}
window.Ye=class{constructor(f,a){this.Wc=f;this.Rg=a;this.Sa=-1;this.Vb=-Infinity;this.re=()=>{this.Sa=-1;this.Vb=Date.now();this.jb=!0;this.Wc();this.jb=!1};this.Vd=this.jb=!1}f(){N(this);this.re=this.Wc=null}};"use strict";function P(f,a){J(f,"get-element",b=>{const d=f.ca.get(b.elementId);return a(d,b)})}
window.mh=class extends self.Ua{constructor(f,a){super(f,a);this.ca=new Map;this.Vc=!0;L(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ca.get(b);this.Vc&&d.parentElement.removeChild(d);this.ca.delete(b)}}],["set-visible",b=>{this.Vc&&(this.ca.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Vc){var d=this.ca.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ca.get(b.elementId);throw Error("required override");}],["focus",b=>this.Oc(b)],["set-css-style",b=>{this.ca.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ca.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ca.get(b.elementId).removeAttribute(b.name)}]]);P(this,b=>b)}Oc(f){var a=this.ca.get(f.elementId);f.focus?a.focus():a.blur()}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),a=/android/i.test(navigator.userAgent);let b=0;function d(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.ah?new Promise(k=>{const l="c3_resolve_"+b;++b;self[l]=k;c.textContent=m.gh+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let h=!1,n=!1;function q(){if(!h){try{new Worker("blob://",{get type(){n=
!0}})}catch(m){}h=!0}return n}let v=new Audio;const B={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};v=null;async function E(m){m=await y(m);return(new TextDecoder("utf-8")).decode(m)}
function y(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=p=>c(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(m)})}const z=[];let C=0;window.RealFile=window.File;const F=[],A=new Map,G=new Map;let I=0;const K=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");K.push(m)};const e=new Set(["cordova","playable-ad","instant-games"]);let g=!1;window.wa=class m{constructor(c){this.da=c.ih;this.ra=null;this.Y="";this.kc=c.fh;
this.zb={};this.La=this.yb=null;this.Sb=[];this.D=this.Qa=null;this.dd=!1;this.Yd=0;this.mb=null;this.Pa=-1;this.Wg=()=>this.ag();this.Oa=[];this.s=c.se;this.kb="file"===location.protocol.substr(0,4);!this.da||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&q()||(this.da=!1);if("playable-ad"===this.s||"instant-games"===this.s)this.da=!1;if("cordova"===this.s&&this.da)if(a){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.da=!1)}else this.da=!1;this.Yb=
this.ja=null;"html5"!==this.s&&"playable-ad"!==this.s||!this.kb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.s||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",
k=>this.Gf(k));this.C("runtime","create-job-worker",()=>this.Hf());"cordova"===this.s?document.addEventListener("deviceready",()=>this.Hd(c)):this.Hd(c)}f(){this.Bc();this.ra&&(this.ra=this.ra.onmessage=null);this.yb&&(this.yb.terminate(),this.yb=null);this.La&&(this.La.f(),this.La=null);this.D&&(this.D.parentElement.removeChild(this.D),this.D=null)}Te(){return f&&"cordova"===this.s}vc(){const c=navigator.userAgent;return f&&e.has(this.s)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}Re(){return a}wd(){return a&&
e.has(this.s)}async Hd(c){"macos-wkwebview"===this.s&&this.Sc({type:"ready"});if("playable-ad"===this.s){this.ja=self.c3_base64files;this.Yb={};await this.nf();for(let l=0,p=c.Ta.length;l<p;++l){var k=c.Ta[l].toLowerCase();this.Yb.hasOwnProperty(k)?c.Ta[l]={ah:!0,gh:this.Yb[k]}:this.ja.hasOwnProperty(k)&&(c.Ta[l]=URL.createObjectURL(this.ja[k]))}}c.eh?this.Y=c.eh:(k=location.origin,this.Y=("null"===k?"file:///":k)+location.pathname,k=this.Y.lastIndexOf("/"),-1!==k&&(this.Y=this.Y.substr(0,k+1)));
c.kh&&(this.zb=c.kh);k=new MessageChannel;this.ra=k.port1;this.ra.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Uf(l));this.mb=new self.Ue(this);await Q(this.mb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((l,p)=>{window.AndroidFullScreen.immersiveMode(l,p)})}catch(l){console.error("Failed to enter Android immersive mode: ",l)}this.da?await this.Bf(c,
k.port2):await this.Af(c,k.port2)}Ec(c){c=this.zb.hasOwnProperty(c)?this.zb[c]:c.endsWith("/workermain.js")&&this.zb.hasOwnProperty("workermain.js")?this.zb["workermain.js"]:"playable-ad"===this.s&&this.ja.hasOwnProperty(c.toLowerCase())?this.ja[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async pc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.s&&this.kb)return c=await this.Bb(l.$g?c:this.kc+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),
l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}pa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}Gd(c){var k=this.Y,l=location.href,p=this.pa(),u=this.ga(),r=window.devicePixelRatio,t=m.Xa(),x=c.sh,D=window.cr_previewImageBlobs||this.ja,U=window.cr_previewProjectFileBlobs,V=window.cr_previewProjectFiles,W=window.qh||
"";c=c.se;var X=(new URLSearchParams(self.location.search)).has("debug"),O=this.mb;return{runtimeBaseUrl:k,previewUrl:l,windowInnerWidth:p,windowInnerHeight:u,devicePixelRatio:r,isFullscreen:t,projectData:x,previewImageBlobs:D,previewProjectFileBlobs:U,previewProjectFileSWUrls:V,swClientId:W,exportType:c,isDebug:X,ife:!!self.rh,jobScheduler:{inputPort:O.cd,outputPort:O.jd,maxNumWorkers:O.Tg},supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.kc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.kc+"opus.wasm.wasm",isFileProtocol:this.kb,isiOSCordova:this.Te(),isiOSWebView:this.vc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Bf(c,k){var l=this.Ec(c.jh);this.yb=await this.pc(l,this.Y,{type:"module",name:"Runtime",$g:!0});this.D=document.createElement("canvas");this.D.style.display="none";l=this.D.transferControlToOffscreen();document.body.appendChild(this.D);window.c3canvas=this.D;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let p=c.od||[],u=c.Ta;
p=await Promise.all(p.map(r=>this.Fa(r)));u=await Promise.all(u.map(r=>this.Fa(r)));if("cordova"===this.s)for(let r=0,t=c.nc.length;r<t;++r){const x=c.nc[r],D=x[0];if(D===c.md||"scriptsInEvents.js"===D||D.endsWith("/scriptsInEvents.js"))x[1]=await this.Fa(D)}this.yb.postMessage(Object.assign(this.Gd(c),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:p,engineScripts:u,projectScripts:c.nc,mainProjectScript:c.md,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,
l,...R(this.mb)]);this.Sb=F.map(r=>new r(this));this.Fd();self.c3_callFunction=(r,t)=>this.Qa.Cf(r,t);"preview"===this.s&&(self.goToLastErrorScript=()=>this.Eb("runtime","go-to-last-error-script"))}async Af(c,k){this.D=document.createElement("canvas");this.D.style.display="none";document.body.appendChild(this.D);window.c3canvas=this.D;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Sb=F.map(r=>new r(this));this.Fd();var l=c.Ta.map(r=>"string"===typeof r?(new URL(r,this.Y)).toString():
r);Array.isArray(c.od)&&l.unshift(...c.od);l=await Promise.all(l.map(r=>this.Fa(r)));await Promise.all(l.map(r=>d(r)));l=self.C3_ProjectScriptsStatus;const p=c.md,u=c.nc;for(let [r,t]of u)if(t||(t=r),r===p)try{t=await this.Fa(t),await d(t),"preview"!==this.s||l[r]||this.Qd(r,"main script did not run to completion")}catch(x){this.Qd(r,x)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))t=await this.Fa(t),await d(t);"preview"===this.s&&"object"!==typeof self.lh.nh?(this.Nb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Gd(c),{isInWorker:!1,messagePort:k,canvas:this.D,runOnStartupFunctions:K}),this.Jd(),this.La=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.La,c))}Qd(c,k){this.Nb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Jd(){this.Nb()}Nb(){const c=
window.Xg;c&&(c.parentElement.removeChild(c),window.Xg=null)}async Hf(){const c=await S(this.mb);return{outputPort:c,transferables:[c]}}zf(){if(this.da)throw Error("not available in worker mode");return this.La}Eb(c,k,l,p,u){this.ra.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:null},u)}yd(c,k,l,p,u){const r=I++,t=new Promise((x,D)=>{G.set(r,{resolve:x,reject:D})});this.ra.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:r},
u);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.Mf(c);if("result"===k)this.dg(c);else if("runtime-ready"===k)this.eg();else if("alert-error"===k)this.Nb(),alert(c.message);else if("creating-runtime"===k)this.Jd();else throw Error(`unknown message '${k}'`);}Mf(c){const k=c.component,l=c.handler,p=c.data,u=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(p)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==u&&this.Mb(u,!1,""+t);return}if(null===
u)return r;r&&r.then?r.then(t=>this.Mb(u,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Mb(u,!1,""+t)}):this.Mb(u,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Mb(c,k,l){let p;l&&l.transferables&&(p=l.transferables);this.ra.postMessage({type:"result",responseId:c,isOk:k,result:l},p)}dg(c){const k=c.responseId,l=c.isOk;c=c.result;const p=G.get(k);l?p.resolve(c):p.reject(c);G.delete(k)}C(c,
k,l){let p=A.get(c);p||(p=new Map,A.set(c,p));if(p.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);p.set(k,l)}static Ab(c){if(F.includes(c))throw Error("DOM handler already added");F.push(c)}Fd(){for(const c of this.Sb)if("runtime"===c.eb){this.Qa=c;return}throw Error("cannot find runtime DOM handler");}Uf(c){this.Eb("debugger","message",c)}eg(){for(const c of this.Sb)c.pd()}static Xa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
g)}static Ob(c){g=!!c}hf(c){this.Oa.push(c);this.Rc()}qg(c){c=this.Oa.indexOf(c);if(-1===c)throw Error("invalid callback");this.Oa.splice(c,1);this.Oa.length||this.Bc()}Rc(){-1===this.Pa&&this.Oa.length&&(this.Pa=requestAnimationFrame(this.Wg))}Bc(){-1!==this.Pa&&(cancelAnimationFrame(this.Pa),this.Pa=-1)}ag(){this.Pa=-1;for(const c of this.Oa)c();this.Rc()}xa(c){this.Qa.xa(c)}Da(c){this.Qa.Da(c)}Qc(){this.Qa.Qc()}Hb(c){this.Qa.Hb(c)}Se(){return!!B["audio/webm; codecs=opus"]}async Pg(c){c=await this.yd("runtime",
"opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}af(c){this.dd=!0;this.Yd=c}Qe(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}xd(c){return!this.Qe(c)}async Fa(c){return"cordova"===this.s&&(c.startsWith("file:")||this.kb&&this.xd(c))?(c.startsWith(this.Y)&&(c=c.substr(this.Y.length)),c=await this.Bb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async Gf(c){const k=c.filename;switch(c.as){case "text":return await this.Je(k);
case "buffer":return await this.Bb(k);default:throw Error("unsupported type");}}sd(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(l,p)},p)})}async Je(c){c=await this.sd(c);return await E(c)}Cc(){if(z.length&&!(8<=C)){C++;var c=z.shift();this.pf(c.filename,c.hh,c.Zg)}}Bb(c){return new Promise((k,l)=>{z.push({filename:c,hh:p=>{C--;this.Cc();k(p)},Zg:p=>{C--;this.Cc();l(p)}});this.Cc()})}async pf(c,k,
l){try{const p=await this.sd(c),u=await y(p);k(u)}catch(p){l(p)}}Sc(c){if("windows-webview2"===this.s)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.s)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async nf(){const c=[];for(const [k,l]of Object.entries(this.ja))c.push(this.mf(k,l));await Promise.all(c)}async mf(c,k){if("object"===typeof k)this.ja[c]=new Blob([k.str],{type:k.type}),this.Yb[c]=
k.str;else{let l=await this.xf(k);l||(l=this.rf(k));this.ja[c]=l}}async xf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}rf(c){c=this.kg(c);return this.lf(c.data,c.bh)}kg(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);
k=c.substring(5,k).split(";");c=k[0]||"";const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{bh:c,data:l}}lf(c,k){var l=c.length;let p=l>>2,u=new Uint8Array(l),r=new Uint32Array(u.buffer,0,p),t,x;for(x=t=0;t<p;++t)r[t]=c.charCodeAt(x++)|c.charCodeAt(x++)<<8|c.charCodeAt(x++)<<16|c.charCodeAt(x++)<<24;for(l&=3;l--;)u[x]=c.charCodeAt(x),++x;return new Blob([u],{type:k})}}}"use strict";
{const f=self.wa;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},h={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(e){return new Promise((g,m)=>{const c=document.createElement("link");c.onload=()=>g(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=e;document.head.appendChild(c)})}function v(e){return new Promise((g,m)=>{const c=new Image;c.onload=()=>g(c);c.onerror=k=>m(k);c.src=e})}async function B(e){e=URL.createObjectURL(e);try{return await v(e)}finally{URL.revokeObjectURL(e)}}function E(e){return new Promise((g,m)=>{let c=new FileReader;c.onload=k=>g(k.target.result);c.onerror=k=>m(k);c.readAsText(e)})}async function y(e,g,m){if(!/firefox/i.test(navigator.userAgent))return await B(e);var c=await E(e);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),p=k.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await B(e)}k.setAttribute("width",g+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);e=new Blob([c],{type:"image/svg+xml"});return await B(e)}function z(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),F=new Set(["canvas","body","html"]);function A(e){F.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function G(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await B(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const g=e.getBoundingClientRect();document.body.removeChild(e);return[g.width,
g.height]}};self.C3_RasterSvgImageBlob=async function(e,g,m,c,k){e=await y(e,g,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(e,0,0,g,m);return l};let I=!1;document.addEventListener("pause",()=>I=!0);document.addEventListener("resume",()=>I=!1);function K(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.Ab(class extends self.Ua{constructor(e){super(e,"runtime");this.de=!0;this.Ra=-1;this.kd="any";this.Rd=this.Sd=!1;this.za=
null;this.W=!1;this.Zd="";this.Zc=-1;this.Ka=this.ub=null;this.fc=this.ec=0;this.Xd=!1;this.he=e.pa();this.Wb=e.ga();this.wb=0;e.C("canvas","update-size",c=>this.hg(c));e.C("runtime","invoke-download",c=>this.Sf(c));e.C("runtime","raster-svg-image",c=>this.bg(c));e.C("runtime","get-svg-image-size",c=>this.Qf(c));e.C("runtime","set-target-orientation",c=>this.fg(c));e.C("runtime","register-sw",()=>this.cg());e.C("runtime","post-to-debugger",c=>this.Md(c));e.C("runtime","go-to-script",c=>this.Md(c));
e.C("runtime","before-start-ticking",()=>this.Ff());e.C("runtime","debug-highlight",c=>this.If(c));e.C("runtime","enable-device-orientation",()=>this.kf());e.C("runtime","enable-device-motion",()=>this.jf());e.C("runtime","add-stylesheet",c=>this.Ef(c));e.C("runtime","alert",c=>this.Ic(c));e.C("runtime","hide-cordova-splash",()=>this.Rf());e.C("runtime","set-exporting-to-video",c=>this.wg(c));e.C("runtime","export-to-video-progress",c=>this.Nf(c));e.C("runtime","exported-to-video",c=>this.Of(c));
const g=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const k=c.target;g.has(k.tagName.toLowerCase())||z(k)||c.preventDefault()});const m=e.D;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",
A)):m.addEventListener("touchstart",A);this.rb=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",G,{passive:!1});window.addEventListener("wheel",G,{passive:!1});window.addEventListener("resize",()=>this.ig());window.addEventListener("fullscreenchange",()=>this.Za());window.addEventListener("webkitfullscreenchange",()=>this.Za());window.addEventListener("mozfullscreenchange",()=>this.Za());window.addEventListener("fullscreenerror",c=>
this.Lc(c));window.addEventListener("webkitfullscreenerror",c=>this.Lc(c));window.addEventListener("mozfullscreenerror",c=>this.Lc(c));if(e.vc())if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const k=window.visualViewport.height;k>c&&(document.scrollingElement.scrollTop=0);c=k})}else window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||"text"):z(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.jg(c);this.Ma=new Set;this.$b=new WeakSet;this.qa=!1}Ff(){self.setTimeout(()=>{this.Xd=!0},1E3);"cordova"===this.u.s?(document.addEventListener("pause",()=>this.Pc(!0)),document.addEventListener("resume",()=>this.Pc(!1))):document.addEventListener("visibilitychange",()=>this.Pc(document.hidden));return{isSuspended:!(!document.hidden&&!I)}}pd(){window.addEventListener("focus",
()=>this.ab("window-focus"));window.addEventListener("blur",()=>{this.ab("window-blur",{parentHasFocus:K()});this.rb=0});window.addEventListener("focusin",g=>{g=g.target;(C.has(g.tagName.toLowerCase())||z(g))&&this.ab("keyboard-blur")});window.addEventListener("keydown",g=>this.Kd("keydown",g));window.addEventListener("keyup",g=>this.Kd("keyup",g));window.addEventListener("dblclick",g=>this.Mc("dblclick",g,d));window.addEventListener("wheel",g=>this.Wf(g));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
g=>{this.Fc(g);this.$a("pointerdown",g)}),this.u.da&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.ub=new self.Ye(()=>this.uf(),5),this.ub.Vd=!0,window.addEventListener("pointerrawupdate",g=>this.$f(g))):window.addEventListener("pointermove",g=>this.$a("pointermove",g)),window.addEventListener("pointerup",g=>this.$a("pointerup",g)),window.addEventListener("pointercancel",g=>this.$a("pointercancel",g))):(window.addEventListener("mousedown",g=>{this.Fc(g);this.Nc("pointerdown",
g)}),window.addEventListener("mousemove",g=>this.Nc("pointermove",g)),window.addEventListener("mouseup",g=>this.Nc("pointerup",g)),window.addEventListener("touchstart",g=>{this.Fc(g);this.Lb("pointerdown",g)}),window.addEventListener("touchmove",g=>this.Lb("pointermove",g)),window.addEventListener("touchend",g=>this.Lb("pointerup",g)),window.addEventListener("touchcancel",g=>this.Lb("pointercancel",g)));const e=()=>this.Qc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0);this.u.Re()&&!this.u.wd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this.Jc(this.ga(),navigator.virtualKeyboard.boundingRect.height)}))}Jc(e,g){document.body.style.transform="";if(0<g){var m=document.activeElement;m&&(m=m.getBoundingClientRect(),e=(m.top+m.bottom)/2-(e-g)/
2,e>g&&(e=g),0>e&&(e=0),0<e&&(document.body.style.transform=`translateY(${-e}px)`))}}ab(e,g){w(this,e,g||null,n)}pa(){return this.u.pa()}ga(){return this.u.ga()}ig(){if(!this.W){var e=this.pa(),g=this.ga();if(this.u.wd()){if(this.Xd){if(this.he===e&&g<this.Wb){this.wb=this.Wb-g;this.Jc(this.Wb,this.wb);return}0<this.wb&&(this.wb=0,this.Jc(g,this.wb))}this.he=e;this.Wb=g}this.ab("window-resize",{innerWidth:e,innerHeight:g,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Xa()});this.u.vc()&&
(-1!==this.Ra&&clearTimeout(this.Ra),this.Nd(e,g,0))}}rg(e,g,m){-1!==this.Ra&&clearTimeout(this.Ra);this.Ra=setTimeout(()=>this.Nd(e,g,m),48)}Nd(e,g,m){const c=this.pa(),k=this.ga();this.Ra=-1;c!=e||k!=g?this.ab("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Xa()}):10>m&&this.rg(c,k,m+1)}fg(e){this.kd=e.targetOrientation}Lg(){const e=this.kd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(g=>console.warn("[Construct 3] Failed to lock orientation: ",
g));else try{let g=!1;screen.lockOrientation?g=screen.lockOrientation(e):screen.webkitLockOrientation?g=screen.webkitLockOrientation(e):screen.mozLockOrientation?g=screen.mozLockOrientation(e):screen.msLockOrientation&&(g=screen.msLockOrientation(e));g||console.warn("[Construct 3] Failed to lock orientation")}catch(g){console.warn("[Construct 3] Failed to lock orientation: ",g)}}Za(){if(!this.W){var e=f.Xa();e&&"any"!==this.kd&&this.Lg();w(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.pa(),
innerHeight:this.ga()})}}Lc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);w(this,"fullscreenerror",{isFullscreen:f.Xa(),innerWidth:this.pa(),innerHeight:this.ga()})}Pc(e){e?this.u.Bc():this.u.Rc();w(this,"visibilitychange",{hidden:e})}Kd(e,g){"Backspace"===g.key&&A(g);if(!this.W){var m=b.get(g.code)||g.code;H(this,e,{code:m,key:g.key,which:g.which,repeat:g.repeat,altKey:g.altKey,ctrlKey:g.ctrlKey,metaKey:g.metaKey,shiftKey:g.shiftKey,timeStamp:g.timeStamp},d)}}Wf(e){this.W||w(this,
"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},d)}Mc(e,g,m){this.W||a(g)||H(this,e,{button:g.button,buttons:g.buttons,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,movementX:g.movementX||0,movementY:g.movementY||0,timeStamp:g.timeStamp},m)}Nc(e,g){if(!this.W&&!a(g)){var m=this.rb;"pointerdown"===e&&0!==m?e="pointermove":"pointerup"===e&&0!==g.buttons&&(e="pointermove");
H(this,e,{pointerId:1,pointerType:"mouse",button:g.button,buttons:g.buttons,lastButtons:m,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,movementX:g.movementX||0,movementY:g.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:g.timeStamp},d);this.rb=g.buttons;this.Mc(g.type,g,h)}}$a(e,g){if(!this.W){if(this.ub&&"pointermove"!==e){var m=this.ub;m.jb||(N(m),m.Vb=Date.now())}m=0;"mouse"===g.pointerType&&(m=this.rb);H(this,e,{pointerId:g.pointerId,
pointerType:g.pointerType,button:g.button,buttons:g.buttons,lastButtons:m,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,movementX:(g.movementX||0)+this.ec,movementY:(g.movementY||0)+this.fc,width:g.width||0,height:g.height||0,pressure:g.pressure||0,tangentialPressure:g.tangentialPressure||0,tiltX:g.tiltX||0,tiltY:g.tiltY||0,twist:g.twist||0,timeStamp:g.timeStamp},d);this.fc=this.ec=0;"mouse"===g.pointerType&&(m="mousemove","pointerdown"===e?m="mousedown":"pointerup"===e&&(m="mouseup"),
this.Mc(m,g,h),this.rb=g.buttons)}}$f(e){this.Ka&&(this.ec+=this.Ka.movementX||0,this.fc+=this.Ka.movementY||0);this.Ka=e;e=this.ub;if(-1===e.Sa){var g=Date.now(),m=g-e.Vb,c=e.Rg;m>=c&&e.Vd?(e.Vb=g,e.jb=!0,e.Wc(),e.jb=!1):e.Sa=self.setTimeout(e.re,Math.max(c-m,4))}}uf(){this.$a("pointermove",this.Ka);this.Ka=null}Lb(e,g){if(!this.W)for(let m=0,c=g.changedTouches.length;m<c;++m){const k=g.changedTouches[m];H(this,e,{pointerId:k.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,
clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,movementX:g.movementX||0,movementY:g.movementY||0,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:g.timeStamp},d)}}Fc(e){window!==window.top&&window.focus();this.Id(e.target)&&document.activeElement&&!this.Id(document.activeElement)&&document.activeElement.blur()}Id(e){return!e||e===document||e===window||e===document.body||
"canvas"===e.tagName.toLowerCase()}kf(){this.Sd||(this.Sd=!0,window.addEventListener("deviceorientation",e=>this.Kf(e)),window.addEventListener("deviceorientationabsolute",e=>this.Lf(e)))}jf(){this.Rd||(this.Rd=!0,window.addEventListener("devicemotion",e=>this.Jf(e)))}Kf(e){this.W||w(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}Lf(e){this.W||
w(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}Jf(e){if(!this.W){var g=null,m=e.acceleration;m&&(g={x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=e.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var k=e.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});w(this,"devicemotion",{acceleration:g,accelerationIncludingGravity:m,rotationRate:c,interval:e.interval,timeStamp:e.timeStamp},
d)}}hg(e){var g=this.u;g.dd||(g=g.D,g.style.width=e.styleWidth+"px",g.style.height=e.styleHeight+"px",g.style.marginLeft=e.marginLeft+"px",g.style.marginTop=e.marginTop+"px",this.de&&(g.style.display="",this.de=!1))}Sf(e){const g=e.url;e=e.filename;const m=document.createElement("a"),c=document.body;m.textContent=e;m.href=g;m.download=e;c.appendChild(m);m.click();c.removeChild(m)}async bg(e){var g=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,
e.surfaceHeight);g=g?await createImageBitmap(e,g):await createImageBitmap(e);return{imageBitmap:g,transferables:[g]}}async Qf(e){return await self.C3_GetSvgImageSize(e.blob)}async Ef(e){await q(e.url)}Qc(){var e=[...this.Ma];this.Ma.clear();if(!this.qa)for(const g of e)(e=g.play())&&e.catch(()=>{this.$b.has(g)||this.Ma.add(g)})}xa(e){if("function"!==typeof e.play)throw Error("missing play function");this.$b.delete(e);let g;try{g=e.play()}catch(m){this.Ma.add(e);return}g&&g.catch(()=>{this.$b.has(e)||
this.Ma.add(e)})}Da(e){this.Ma.delete(e);this.$b.add(e)}Hb(e){this.qa=!!e}Rf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}If(e){if(e.show){this.za||(this.za=document.createElement("div"),this.za.id="inspectOutline",document.body.appendChild(this.za));var g=this.za;g.style.display="";g.style.left=e.left-1+"px";g.style.top=e.top-1+"px";g.style.width=e.width+2+"px";g.style.height=e.height+2+"px";g.textContent=e.name}else this.za&&(this.za.style.display="none")}cg(){window.C3_RegisterSW&&
window.C3_RegisterSW()}Md(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}Cf(e,g){return this.u.yd(this.eb,"js-invoke-function",{name:e,params:g},void 0,void 0)}Ic(e){alert(e.message)}jg(e){"entered-fullscreen"===e?(f.Ob(!0),this.Za()):"exited-fullscreen"===e?(f.Ob(!1),this.Za()):console.warn("Unknown wrapper message: ",e)}wg(e){this.W=!0;const g=document.createElement("h1");g.id="exportToVideoMessage";g.textContent=e.message;document.body.prepend(g);document.body.classList.add("exportingToVideo");
this.u.D.style.display="";this.u.af(e.duration)}Nf(e){this.Zd=e.message;-1===this.Zc&&(this.Zc=setTimeout(()=>this.vf(),250))}vf(){this.Zc=-1;const e=document.getElementById("exportToVideoMessage");e&&(e.textContent=this.Zd)}Of(e){window.ph({type:"exported-video",blob:e.blob,time:e.time})}})}"use strict";
async function Q(f){if(f.Qg)throw Error("already initialised");f.Qg=!0;var a=f.jc.Ec("dispatchworker.js");f.Yc=await f.jc.pc(a,f.cb,{name:"DispatchWorker"});a=new MessageChannel;f.cd=a.port1;f.Yc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.jd=await S(f)}function R(f){return[f.cd,f.jd]}
async function S(f){const a=f.ee.length;var b=f.jc.Ec("jobworker.js");b=await f.jc.pc(b,f.cb,{name:"JobWorker"+a});const d=new MessageChannel,h=new MessageChannel;f.Yc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":h.port2},[d.port2,h.port2]);f.ee.push(b);return h.port1}
self.Ue=class{constructor(f){this.jc=f;this.cb=f.Y;this.cb="preview"===f.s?this.cb+"workers/":this.cb+f.kc;this.Tg=Math.min(navigator.hardwareConcurrency||2,16);this.Yc=null;this.ee=[];this.jd=this.cd=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.wa({ih:!0,jh:"workermain.js",Ta:["scripts/c3runtime.js"],nc:[],md:"",fh:"scripts/",od:[],se:"html5"}));"use strict";
async function T(f,a){a=a.type;let b=!0;0===a?b=await aa():1===a&&(b=await ba());w(f,"permission-result",{type:a,result:b})}async function aa(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}
async function ba(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}self.wa.Ab(class extends self.Ua{constructor(f){super(f,"touch");J(this,"request-permission",a=>T(this,a))}});"use strict";
{const f=180/Math.PI;self.ea=class extends self.Ua{constructor(a){super(a,"audio");this.Ia=this.a=null;this.Tb=this.bd=!1;this.ta=()=>this.Mg();this.aa=[];this.J=[];this.ia=null;this.fe="";this.ge=-1;this.tb=new Map;this.Zb=1;this.qa=!1;this.ld=0;this.lc=1;this.$c=0;this.je="HRTF";this.Wd="inverse";this.ke=600;this.ie=1E4;this.me=1;this.ae=this.cc=!1;this.pe=this.u.Se();this.ba=new Map;this.Ha=new Set;this.be=this.ed=!1;this.gd="";this.Aa=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Vf(b,d);this.Rb=
null;self.C3Audio_GetOutputStream=()=>this.Pf();self.C3Audio_DOMInterface=this;L(this,[["create-audio-context",b=>this.qf(b)],["play",b=>this.lg(b)],["stop",b=>this.Jg(b)],["stop-all",()=>this.Kg()],["set-paused",b=>this.Cg(b)],["set-volume",b=>this.Hg(b)],["fade-volume",b=>this.wf(b)],["set-master-volume",b=>this.Ag(b)],["set-muted",b=>this.Bg(b)],["set-silent",b=>this.Eg(b)],["set-looping",b=>this.zg(b)],["set-playback-rate",b=>this.Dg(b)],["seek",b=>this.sg(b)],["preload",b=>this.mg(b)],["unload",
b=>this.Ng(b)],["unload-all",()=>this.Og()],["set-suspended",b=>this.Fg(b)],["add-effect",b=>this.Dd(b)],["set-effect-param",b=>this.vg(b)],["remove-effects",b=>this.og(b)],["tick",b=>this.gg(b)],["load-state",b=>this.Tf(b)],["offline-render-audio",b=>this.Xf(b)],["offline-render-finish",()=>this.Zf()]])}async qf(a){a.isiOSCordova&&(this.cc=!0);this.ld=a.timeScaleMode;this.je=["equalpower","HRTF","soundfield"][a.panningModel];this.Wd=["linear","inverse","exponential"][a.distanceModel];this.ke=a.refDistance;
this.ie=a.maxDistance;this.me=a.rolloffFactor;if(this.u.dd)this.cc=!0,this.a=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*this.u.Yd)});else{var b={latencyHint:a.latencyHint};this.pe||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.a=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.a=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.Ed();this.a.onstatechange=()=>{"running"!==this.a.state&&this.Ed();
w(this,"audiocontext-state",{audioContextState:this.a.state})}}this.Ia=this.a.createGain();this.Ia.connect(this.a.destination);b=a.listenerPos;this.a.listener.setPosition(b[0],b[1],b[2]);this.a.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.qc();try{await Promise.all(a.preloadList.map(d=>this.Jb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.a.sampleRate,audioContextState:this.a.state}}Ed(){this.Tb||
(this.bd=!1,window.addEventListener("pointerup",this.ta,!0),window.addEventListener("touchend",this.ta,!0),window.addEventListener("click",this.ta,!0),window.addEventListener("keydown",this.ta,!0),this.Tb=!0)}sf(){this.Tb&&(this.bd=!0,window.removeEventListener("pointerup",this.ta,!0),window.removeEventListener("touchend",this.ta,!0),window.removeEventListener("click",this.ta,!0),window.removeEventListener("keydown",this.ta,!0),this.Tb=!1)}Mg(){if(!this.bd){var a=this.a;"suspended"===a.state&&a.resume&&
a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.sf()}}V(){return this.a}qc(){return this.a.currentTime}ua(){return this.Ia}ud(a){return(a=this.ba.get(a.toLowerCase()))?a[0].O():this.ua()}te(a,b){a=a.toLowerCase();let d=this.ba.get(a);d||(d=[],this.ba.set(a,d));b.yg(d.length);b.Gg(a);d.push(b);this.Pd(a)}Pd(a){let b=this.ua();const d=this.ba.get(a);if(d&&d.length){b=d[0].O();for(let h=0,n=d.length;h<n;++h){const q=
d[h];h+1===n?q.R(this.ua()):q.R(d[h+1].O())}}for(const h of this.na(a))h.Ze(b);this.Aa&&this.gd===a&&(this.Aa.disconnect(),this.Aa.connect(b))}Db(){return this.qa}xg(){this.ae=!0}Le(a,b){return b?this.u.Pg(a).then(d=>{const h=this.a.createBuffer(1,d.length,48E3);h.getChannelData(0).set(d);return h}):new Promise((d,h)=>{this.a.decodeAudioData(a,d,h)})}xa(a){this.u.xa(a)}Da(a){this.u.Da(a)}zd(a){let b=0;for(let d=0,h=this.J.length;d<h;++d){const n=this.J[d];this.J[b]=n;n.K===a?n.f():++b}this.J.length=
b}$e(){let a=0;for(let b=0,d=this.aa.length;b<d;++b){const h=this.aa[b];this.aa[a]=h;h.va()?h.f():++a}this.aa.length=a}*na(a){if(a)for(const b of this.J)self.ea.Me(b.Z,a)&&(yield b);else this.ia&&!this.ia.S()&&(yield this.ia)}async Jb(a,b,d,h,n){for(const q of this.aa)if(q.Wa()===b)return await Y(q),q;if(n)return null;h&&(this.cc||this.ae)&&this.$e();n="audio/webm; codecs=opus"===d&&!this.pe;h&&n&&this.xg();a=!h||this.cc||n?new self.He(this,a,b,d,h,n):new self.Fe(this,a,b,d,h);this.aa.push(a);await Y(a);
return a}async Dc(a,b,d,h,n){for(const q of this.J)if(q.Wa()===b&&(q.oc()||n))return q.cf(h),q;a=await this.Jb(a,b,d,n);h="html5"===a.Uc?new self.Ge(a.j,a,h):new self.Ie(a.j,a,h);this.J.push(h);return h}gf(a){let b=this.tb.get(a);if(!b){let d=null;b={nd:0,dh:new Promise(h=>d=h),resolve:d};this.tb.set(a,b)}b.nd++}pg(a){const b=this.tb.get(a);if(!b)throw Error("expected pending tag");b.nd--;0===b.nd&&(b.resolve(),this.tb.delete(a))}Ac(a){a||(a=this.fe);return(a=this.tb.get(a))?a.dh:Promise.resolve()}Kb(){if(0<
this.Ha.size)M(this);else for(const a of this.J)if(a.vd()){M(this);break}}Ea(){for(var a of this.Ha)a.Ea();a=this.qc();for(var b of this.J)b.Ea(a);b=this.J.filter(d=>d.vd()).map(d=>d.Va());w(this,"state",{tickCount:this.ge,audioInstances:b,analysers:[...this.Ha].map(d=>d.Oe())});0===b.length&&0===this.Ha.size&&this.Ub&&(this.u.qg(this.qe),this.Ub=!1)}wc(a,b,d){w(this,"trigger",{type:a,tag:b,aiid:d})}async lg(a){const b=a.originalUrl,d=a.url,h=a.type,n=a.isMusic,q=a.tag,v=a.isLooping,B=a.vol,E=a.pos,
y=a.panning;let z=a.off;0<z&&!a.trueClock&&(this.a.getOutputTimestamp?(a=this.a.getOutputTimestamp(),z=z-a.performanceTime/1E3+a.contextTime):z=z-performance.now()/1E3+this.a.currentTime);this.fe=q;this.gf(q);try{this.ia=await this.Dc(b,d,h,q,n),y?(this.ia.Gb(!0),this.ia.bf(y.x,y.y,y.angle,y.innerAngle,y.outerAngle,y.outerGain),y.hasOwnProperty("uid")&&this.ia.df(y.uid)):this.ia.Gb(!1),this.ia.Play(v,B,E,z)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.pg(q)}M(this)}Jg(a){a=
a.tag;for(const b of this.na(a))b.oa()}Kg(){for(const a of this.J)a.oa()}Cg(a){const b=a.tag;a=a.paused;for(const d of this.na(b))a?d.Ya():d.Fb();this.Kb()}Hg(a){const b=a.tag;a=a.vol;for(const d of this.na(b))d.Ib(a)}async wf(a){const b=a.tag,d=a.vol,h=a.duration;a=a.stopOnEnd;await this.Ac(b);for(const n of this.na(b))n.Ne(d,h,a);this.Kb()}Ag(a){this.Zb=a.vol;this.Ia.gain.value=this.Zb}Bg(a){const b=a.tag;a=a.isMuted;for(const d of this.na(b))d.Ad(a)}Eg(a){this.qa=a.isSilent;this.u.Hb(this.qa);
for(const b of this.J)b.Pb()}zg(a){const b=a.tag;a=a.isLooping;for(const d of this.na(b))d.yc(a)}async Dg(a){const b=a.tag;a=a.rate;await this.Ac(b);for(const d of this.na(b))d.Cd(a)}async sg(a){const b=a.tag;a=a.pos;await this.Ac(b);for(const d of this.na(b))d.xc(a)}async mg(a){const b=a.originalUrl,d=a.url,h=a.type;a=a.isMusic;try{await this.Dc(b,d,h,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async Ng(a){if(a=await this.Jb("",a.url,a.type,a.isMusic,!0))a.f(),a=this.aa.indexOf(a),
-1!==a&&this.aa.splice(a,1)}Og(){for(const a of this.aa)a.f();this.aa.length=0}Fg(a){a=a.isSuspended;!a&&this.a.resume&&this.a.resume();for(const b of this.J)b.zc(a);a&&this.a.suspend&&this.a.suspend()}gg(a){this.lc=a.timeScale;this.$c=a.gameTime;this.ge=a.tickCount;if(0!==this.ld)for(var b of this.J)b.Ga();(b=a.listenerPos)&&this.a.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const h of this.J)h.ha===a&&h.Bd(d.x,d.y,d.angle)}}async Dd(a){var b=a.type;const d=a.tag;
var h=a.params;if("filter"===b)h=new self.ze(this,...h);else if("delay"===b)h=new self.xe(this,...h);else if("convolution"===b){b=null;try{b=await this.Jb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",n);return}h=new self.we(this,b.$,...h);h.tg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)h=new self.Ae(this,...h);else if("phaser"===b)h=new self.Ce(this,...h);else if("gain"===b)h=new self.Be(this,...h);else if("tremolo"===
b)h=new self.Ee(this,...h);else if("ringmod"===b)h=new self.De(this,...h);else if("distortion"===b)h=new self.ye(this,...h);else if("compressor"===b)h=new self.ve(this,...h);else if("analyser"===b)h=new self.ue(this,...h);else throw Error("invalid effect type");this.te(d,h);this.Od()}vg(a){const b=a.index,d=a.param,h=a.value,n=a.ramp,q=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,h,n,q),this.Od())}og(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const d of b)d.f();
this.ba.delete(a);this.Pd(a)}}ff(a){this.Ha.add(a);this.Kb()}ng(a){this.Ha.delete(a)}Od(){this.ed||(this.ed=!0,Promise.resolve().then(()=>this.tf()))}tf(){const a={};for(const [b,d]of this.ba)a[b]=d.map(h=>h.Va());w(this,"fxstate",{fxstate:a});this.ed=!1}async Tf(a){const b=a.saveLoadMode;if(3!==b)for(var d of this.J)d.va()&&1===b||(d.va()||2!==b)&&d.oa();for(const h of this.ba.values())for(const n of h)n.f();this.ba.clear();this.lc=a.timeScale;this.$c=a.gameTime;d=a.listenerPos;this.a.listener.setPosition(d[0],
d[1],d[2]);this.qa=a.isSilent;this.u.Hb(this.qa);this.Zb=a.masterVolume;this.Ia.gain.value=this.Zb;d=[];for(const h of Object.values(a.effects))d.push(Promise.all(h.map(n=>this.Dd(n))));await Promise.all(d);await Promise.all(a.playing.map(h=>this.Df(h,b)));this.Kb()}async Df(a,b){if(3!==b){var d=a.bufferOriginalUrl,h=a.bufferUrl,n=a.bufferType,q=a.isMusic,v=a.tag,B=a.isLooping,E=a.volume,y=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.Dc(d,h,n,v,q)}catch(z){console.error("[Construct 3] Audio: error loading audio state: ",
z);return}b.Xe(a.pan);b.Play(B,E,y,0);a.isPlaying||b.Ya();b.Hc(a)}}}Vf(a,b){this.Aa&&this.Aa.disconnect();this.gd=b.toLowerCase();this.Aa=this.a.createMediaStreamSource(a);this.Aa.connect(this.ud(this.gd))}Pf(){this.Rb||(this.Rb=this.a.createMediaStreamDestination(),this.Ia.connect(this.Rb));return this.Rb.stream}async Xf(a){try{const b=this.a.suspend(a.time);this.be?this.a.resume():(this.a.startRendering().then(d=>this.Yf(d)).catch(d=>this.Ld(d)),this.be=!0);await b}catch(b){this.Ld(b)}}Zf(){this.a.resume()}Yf(a){const b=
[];for(let d=0,h=a.numberOfChannels;d<h;++d){const n=a.getChannelData(d);b.push(n.buffer)}this.u.Eb("runtime","offline-audio-render-completed",{duration:a.duration,length:a.length,numberOfChannels:a.numberOfChannels,sampleRate:a.sampleRate,channelData:b},null,b)}Ld(a){console.error("[Audio] Offline rendering error: ",a)}static Me(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static ef(a){return a*f}static Ke(a){return Math.pow(10,a/20)}static td(a){return Math.max(Math.min(self.ea.Ke(a),
1),0)}static We(a){return Math.log(a)/Math.log(10)*20}static Ve(a){return self.ea.We(Math.max(Math.min(a,1),0))}static Yg(a,b){return 1-Math.exp(-b*a)}};self.wa.Ab(self.ea)}"use strict";function Y(f){f.Xb||(f.Xb=f.Gc());return f.Xb}self.qd=class{constructor(f,a,b,d,h){this.j=f;this.Vg=a;this.Ba=b;this.P=d;this.Sg=h;this.Uc="";this.Xb=null}f(){this.Xb=this.j=null}Gc(){}V(){return this.j.V()}sc(){return this.Vg}Wa(){return this.Ba}rc(){return this.P}va(){return this.Sg}fa(){}};"use strict";
self.Fe=class extends self.qd{constructor(f,a,b,d,h){super(f,a,b,d,h);this.Uc="html5";this.I=new Audio;this.I.crossOrigin="anonymous";this.I.autoplay=!1;this.I.preload="auto";this.nb=this.ob=null;this.I.addEventListener("canplaythrough",()=>!0);this.sb=this.V().createGain();this.qb=null;this.I.addEventListener("canplay",()=>{this.ob&&(this.ob(),this.nb=this.ob=null);!this.qb&&this.I&&(this.qb=this.V().createMediaElementSource(this.I),this.qb.connect(this.sb))});this.onended=null;this.I.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.I.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.Ba}' error: `,n);this.nb&&(this.nb(n),this.nb=this.ob=null)})}f(){this.j.zd(this);this.sb.disconnect();this.sb=null;this.qb.disconnect();this.qb=null;this.I&&!this.I.paused&&this.I.pause();this.I=this.onended=null;super.f()}Gc(){return new Promise((f,a)=>{this.ob=f;this.nb=a;this.I.src=this.Ba})}N(){return this.I}fa(){return this.I.duration}};"use strict";
async function ca(f){if(f.ya)return f.ya;var a=f.j.u;if("cordova"===a.s&&a.xd(f.Ba)&&a.kb)f.ya=await a.Bb(f.Ba);else{a=await fetch(f.Ba);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.ya=await a.arrayBuffer()}}async function da(f){if(f.$)return f.$;f.$=await f.j.Le(f.ya,f.Ug);f.ya=null}
self.He=class extends self.qd{constructor(f,a,b,d,h,n){super(f,a,b,d,h);this.Uc="webaudio";this.$=this.ya=null;this.Ug=!!n}f(){this.j.zd(this);this.$=this.ya=null;super.f()}async Gc(){try{await ca(this),await da(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.Ba}': `,f)}}fa(){return this.$?this.$.duration:0}};"use strict";
{let f=0;self.rd=class{constructor(a,b,d){this.j=a;this.K=b;this.Z=d;this.Qb=f++;this.L=this.V().createGain();this.L.connect(this.ua());this.B=null;this.lb=!1;this.la=[0,0,0];this.ka=[0,0,0];this.G=!0;this.U=this.ma=this.F=!1;this.xb=1;this.Ja=!1;this.sa=1;a=this.j.ld;this.fd=1===a&&!this.va()||2===a;this.hb=this.ha=-1;this.oe=!1}f(){this.K=this.j=null;this.B&&(this.B.disconnect(),this.B=null);this.L.disconnect();this.L=null}V(){return this.j.V()}ua(){return this.j.ud(this.Z)}Cb(){return this.fd?
this.j.$c:performance.now()/1E3}sc(){return this.K.sc()}Wa(){return this.K.Wa()}rc(){return this.K.rc()}va(){return this.K.va()}cf(a){this.Z=a}S(){}oc(){}IsPlaying(){return!this.G&&!this.F&&!this.S()}vd(){return!this.G&&!this.S()}Ca(){}fa(){return this.K.fa()}Play(){}oa(){}Ya(){}Fb(){}Ib(a){this.xb=a;this.L.gain.cancelScheduledValues(0);this.hb=-1;this.L.gain.value=this.tc()}Ne(a,b,d){if(!this.Ja){var h=this.L.gain;h.cancelScheduledValues(0);var n=this.j.qc();b=n+b;h.setValueAtTime(h.value,n);h.linearRampToValueAtTime(a,
b);this.xb=a;this.hb=b;this.oe=d}}Tc(){this.Ib(this.xb)}Ea(a){-1!==this.hb&&a>=this.hb&&(this.hb=-1,this.oe&&this.oa(),this.j.wc("fade-ended",this.Z,this.Qb))}tc(){const a=this.xb;return isFinite(a)?a:0}Ad(a){a=!!a;this.Ja!==a&&(this.Ja=a,this.Pb())}Db(){return this.j.Db()}Pb(){}yc(){}Cd(a){this.sa!==a&&(this.sa=a,this.Ga())}Ga(){}xc(){}zc(){}Gb(a){a=!!a;this.lb!==a&&((this.lb=a)?(this.B||(this.B=this.V().createPanner(),this.B.panningModel=this.j.je,this.B.distanceModel=this.j.Wd,this.B.refDistance=
this.j.ke,this.B.maxDistance=this.j.ie,this.B.rolloffFactor=this.j.me),this.L.disconnect(),this.L.connect(this.B),this.B.connect(this.ua())):(this.B.disconnect(),this.L.disconnect(),this.L.connect(this.ua())))}bf(a,b,d,h,n,q){this.lb&&(this.Bd(a,b,d),a=self.ea.ef,this.B.coneInnerAngle=a(h),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=q)}Bd(a,b,d){this.lb&&(this.la[0]=a,this.la[1]=b,this.la[2]=0,this.ka[0]=Math.cos(d),this.ka[1]=Math.sin(d),this.ka[2]=0,this.B.setPosition(...this.la),this.B.setOrientation(...this.ka))}df(a){this.ha=
a}uc(){}Ze(a){const b=this.B||this.L;b.disconnect();b.connect(a)}Va(){return{aiid:this.Qb,tag:this.Z,duration:this.fa(),volume:this.xb,isPlaying:this.IsPlaying(),playbackTime:this.Ca(),playbackRate:this.sa,uid:this.ha,bufferOriginalUrl:this.sc(),bufferUrl:"",bufferType:this.rc(),isMusic:this.va(),isLooping:this.U,isMuted:this.Ja,resumePosition:this.uc(),pan:this.Pe()}}Hc(a){this.Cd(a.playbackRate);this.Ad(a.isMuted)}Pe(){if(!this.B)return null;const a=this.B;return{pos:this.la,orient:this.ka,cia:a.coneInnerAngle,
coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ha}}Xe(a){if(a){this.Gb(!0);a=this.B;var b=a.pos;this.la[0]=b[0];this.la[1]=b[1];this.la[2]=b[2];b=a.orient;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];a.setPosition(...this.la);a.setOrientation(...this.ka);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ha=a.uid}else this.Gb(!1)}}}"use strict";
self.Ge=class extends self.rd{constructor(f,a,b){super(f,a,b);this.K.sb.connect(this.L);this.K.onended=()=>this.Kc()}f(){this.oa();this.K.sb.disconnect();super.f()}N(){return this.K.N()}Kc(){this.G=!0;this.ha=-1;this.j.wc("ended",this.Z,this.Qb)}S(){return this.N().ended}oc(){return this.G?!0:this.S()}Ca(){let f=this.N().currentTime;this.U||(f=Math.min(f,this.fa()));return f}Play(f,a,b){const d=this.N();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==f&&(d.loop=f);this.Ib(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(h){console.warn(`[Construct 3] Exception seeking audio '${this.K.Wa()}' to position '${b}': `,h)}this.j.xa(d);this.F=this.G=!1;this.U=f;this.sa=1}oa(){const f=this.N();f.paused||f.pause();this.j.Da(f);this.G=!0;this.F=!1;this.ha=-1}Ya(){if(!(this.F||this.G||this.S())){var f=this.N();f.paused||f.pause();this.j.Da(f);this.F=!0}}Fb(){!this.F||this.G||this.S()||(this.j.xa(this.N()),this.F=!1)}Pb(){this.N().muted=this.Ja||this.Db()}yc(f){f=!!f;this.U!==f&&
(this.U=f,this.N().loop=f)}Ga(){let f=this.sa;this.fd&&(f*=this.j.lc);try{this.N().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}xc(f){if(!this.G&&!this.S())try{this.N().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}uc(){return this.Ca()}zc(f){f?this.IsPlaying()?(this.N().pause(),this.ma=!0):this.ma=!1:this.ma&&(this.j.xa(this.N()),this.ma=!1)}};"use strict";
function Z(f){f.i&&f.i.disconnect();f.i=null;f.bb=null}
self.Ie=class extends self.rd{constructor(f,a,b){super(f,a,b);this.i=null;this.ac=d=>this.Kc(d);this.ad=!0;this.bb=null;this.M=this.bc=this.dc=0;this.hd=1}f(){this.oa();Z(this);this.ac=null;super.f()}Kc(f){this.F||this.ma||f.target!==this.bb||(this.G=this.ad=!0,this.ha=-1,Z(this),this.j.wc("ended",this.Z,this.Qb))}S(){return!this.G&&this.i&&this.i.loop||this.F?!1:this.ad}oc(){return!this.i||this.G?!0:this.S()}Ca(){let f;f=this.F?this.M:this.bc+(this.Cb()-this.dc)*this.sa;this.U||(f=Math.min(f,this.fa()));
return f}Play(f,a,b,d){this.hd=1;this.Ib(a);Z(this);this.i=this.V().createBufferSource();this.i.buffer=this.K.$;this.i.connect(this.L);this.bb=this.i;this.i.onended=this.ac;this.i.loop=f;this.i.start(d,b);this.F=this.G=this.ad=!1;this.U=f;this.sa=1;this.dc=this.Cb();this.bc=b}oa(){if(this.i)try{this.i.stop(0)}catch(f){}this.G=!0;this.F=!1;this.ha=-1}Ya(){this.F||this.G||this.S()||(this.M=this.Ca(),this.U&&(this.M%=this.fa()),this.F=!0,this.i.stop(0))}Fb(){!this.F||this.G||this.S()||(Z(this),this.i=
this.V().createBufferSource(),this.i.buffer=this.K.$,this.i.connect(this.L),this.bb=this.i,this.i.onended=this.ac,this.i.loop=this.U,this.Tc(),this.Ga(),this.i.start(0,this.M),this.dc=this.Cb(),this.bc=this.M,this.F=!1)}tc(){return super.tc()*this.hd}Pb(){this.hd=this.Ja||this.Db()?0:1;this.Tc()}yc(f){f=!!f;this.U!==f&&(this.U=f,this.i&&(this.i.loop=f))}Ga(){let f=this.sa;this.fd&&(f*=this.j.lc);this.i&&(this.i.playbackRate.value=f)}xc(f){this.G||this.S()||(this.F?this.M=f:(this.Ya(),this.M=f,this.Fb()))}uc(){return this.M}zc(f){f?
this.IsPlaying()?(this.ma=!0,this.M=this.Ca(),this.U&&(this.M%=this.fa()),this.i.stop(0)):this.ma=!1:this.ma&&(Z(this),this.i=this.V().createBufferSource(),this.i.buffer=this.K.$,this.i.connect(this.L),this.bb=this.i,this.i.onended=this.ac,this.i.loop=this.U,this.Tc(),this.Ga(),this.i.start(0,this.M),this.dc=this.Cb(),this.bc=this.M,this.ma=!1)}Hc(f){super.Hc(f);this.M=f.resumePosition}};"use strict";
{class f{constructor(a){this.j=a;this.a=a.V();this.ce=-1;this.P=this.Z="";this.g=null}f(){this.a=null}yg(a){this.ce=a}Gg(a){this.Z=a}o(){return this.a.createGain()}O(){}R(){}m(a,b,d,h){a.cancelScheduledValues(0);if(0===h)a.value=b;else{var n=this.a.currentTime;h+=n;switch(d){case 0:a.setValueAtTime(b,h);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,h);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,h)}}}Va(){return{type:this.P,tag:this.Z,params:this.g}}}
self.ze=class extends f{constructor(a,b,d,h,n,q,v){super(a);this.P="filter";this.g=[b,d,h,n,q,v];this.l=this.o();this.c=this.o();this.c.gain.value=v;this.b=this.o();this.b.gain.value=1-v;this.A=this.a.createBiquadFilter();this.A.type=b;this.A.frequency.value=d;this.A.detune.value=h;this.A.Q.value=n;this.A.gain.vlaue=q;this.l.connect(this.A);this.l.connect(this.b);this.A.connect(this.c)}f(){this.l.disconnect();this.A.disconnect();this.c.disconnect();this.b.disconnect();super.f()}R(a){this.c.disconnect();
this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.c.gain,b,d,h);this.m(this.b.gain,1-b,d,h);break;case 1:this.g[1]=b;this.m(this.A.frequency,b,d,h);break;case 2:this.g[2]=b;this.m(this.A.detune,b,d,h);break;case 3:this.g[3]=b;this.m(this.A.Q,b,d,h);break;case 4:this.g[4]=b,this.m(this.A.gain,b,d,h)}}};self.xe=class extends f{constructor(a,b,d,h){super(a);this.P="delay";this.g=[b,d,h];this.l=
this.o();this.c=this.o();this.c.gain.value=h;this.b=this.o();this.b.gain.value=1-h;this.pb=this.o();this.T=this.a.createDelay(b);this.T.delayTime.value=b;this.gb=this.o();this.gb.gain.value=d;this.l.connect(this.pb);this.l.connect(this.b);this.pb.connect(this.c);this.pb.connect(this.T);this.T.connect(this.gb);this.gb.connect(this.pb)}f(){this.l.disconnect();this.c.disconnect();this.b.disconnect();this.pb.disconnect();this.T.disconnect();this.gb.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);
this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,b,d,h){const n=self.ea.td;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.c.gain,b,d,h);this.m(this.b.gain,1-b,d,h);break;case 4:this.g[1]=n(b);this.m(this.gb.gain,n(b),d,h);break;case 5:this.g[0]=b,this.m(this.T.delayTime,b,d,h)}}};self.we=class extends f{constructor(a,b,d,h){super(a);this.P="convolution";this.g=[d,h];this.Ud=this.Td="";this.l=this.o();this.c=this.o();this.c.gain.value=h;this.b=this.o();this.b.gain.value=
1-h;this.fb=this.a.createConvolver();this.fb.normalize=d;this.fb.buffer=b;this.l.connect(this.fb);this.l.connect(this.b);this.fb.connect(this.c)}f(){this.l.disconnect();this.fb.disconnect();this.c.disconnect();this.b.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.c.gain,b,d,h),this.m(this.b.gain,1-b,d,h)}}tg(a,b){this.Td=a;this.Ud=b}Va(){const a=
super.Va();a.bufferOriginalUrl=this.Td;a.bufferUrl="";a.bufferType=this.Ud;return a}};self.Ae=class extends f{constructor(a,b,d,h,n,q){super(a);this.P="flanger";this.g=[b,d,h,n,q];this.l=this.o();this.b=this.o();this.b.gain.value=1-q/2;this.c=this.o();this.c.gain.value=q/2;this.ib=this.o();this.ib.gain.value=n;this.T=this.a.createDelay(b+d);this.T.delayTime.value=b;this.v=this.a.createOscillator();this.v.frequency.value=h;this.H=this.o();this.H.gain.value=d;this.l.connect(this.T);this.l.connect(this.b);
this.T.connect(this.c);this.T.connect(this.ib);this.ib.connect(this.T);this.v.connect(this.H);this.H.connect(this.T.delayTime);this.v.start(0)}f(){this.v.stop(0);this.l.disconnect();this.T.disconnect();this.v.disconnect();this.H.disconnect();this.b.disconnect();this.c.disconnect();this.ib.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.c.gain,
b/2,d,h);this.m(this.b.gain,1-b/2,d,h);break;case 6:this.g[1]=b/1E3;this.m(this.H.gain,b/1E3,d,h);break;case 7:this.g[2]=b;this.m(this.v.frequency,b,d,h);break;case 8:this.g[3]=b/100,this.m(this.ib.gain,b/100,d,h)}}};self.Ce=class extends f{constructor(a,b,d,h,n,q,v){super(a);this.P="phaser";this.g=[b,d,h,n,q,v];this.l=this.o();this.b=this.o();this.b.gain.value=1-v/2;this.c=this.o();this.c.gain.value=v/2;this.A=this.a.createBiquadFilter();this.A.type="allpass";this.A.frequency.value=b;this.A.detune.value=
d;this.A.Q.value=h;this.v=this.a.createOscillator();this.v.frequency.value=q;this.H=this.o();this.H.gain.value=n;this.l.connect(this.A);this.l.connect(this.b);this.A.connect(this.c);this.v.connect(this.H);this.H.connect(this.A.frequency);this.v.start(0)}f(){this.v.stop(0);this.l.disconnect();this.A.disconnect();this.v.disconnect();this.H.disconnect();this.b.disconnect();this.c.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,
b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.c.gain,b/2,d,h);this.m(this.b.gain,1-b/2,d,h);break;case 1:this.g[0]=b;this.m(this.A.frequency,b,d,h);break;case 2:this.g[1]=b;this.m(this.A.detune,b,d,h);break;case 3:this.g[2]=b;this.m(this.A.Q,b,d,h);break;case 6:this.g[3]=b;this.m(this.H.gain,b,d,h);break;case 7:this.g[4]=b,this.m(this.v.frequency,b,d,h)}}};self.Be=class extends f{constructor(a,b){super(a);this.P="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}f(){this.h.disconnect();super.f()}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(a,b,d,h){const n=self.ea.td;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,h)}}};self.Ee=class extends f{constructor(a,b,d){super(a);this.P="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.v=this.a.createOscillator();this.v.frequency.value=b;this.H=this.o();this.H.gain.value=d/2;this.v.connect(this.H);this.H.connect(this.h.gain);this.v.start(0)}f(){this.v.stop(0);this.v.disconnect();
this.H.disconnect();this.h.disconnect();super.f()}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,h);this.m(this.H.gain,b/2,d,h);break;case 7:this.g[0]=b,this.m(this.v.frequency,b,d,h)}}};self.De=class extends f{constructor(a,b,d){super(a);this.P="ringmod";this.g=[b,d];this.l=this.o();this.c=this.o();this.c.gain.value=d;this.b=this.o();this.b.gain.value=1-d;this.vb=this.o();this.vb.gain.value=
0;this.v=this.a.createOscillator();this.v.frequency.value=b;this.v.connect(this.vb.gain);this.v.start(0);this.l.connect(this.vb);this.l.connect(this.b);this.vb.connect(this.c)}f(){this.v.stop(0);this.v.disconnect();this.vb.disconnect();this.l.disconnect();this.c.disconnect();this.b.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.c.gain,b,d,h);
this.m(this.b.gain,1-b,d,h);break;case 7:this.g[0]=b,this.m(this.v.frequency,b,d,h)}}};self.ye=class extends f{constructor(a,b,d,h,n,q){super(a);this.P="distortion";this.g=[b,d,h,n,q];this.l=this.o();this.ic=this.o();this.hc=this.o();this.ug(h,n);this.c=this.o();this.c.gain.value=q;this.b=this.o();this.b.gain.value=1-q;this.mc=this.a.createWaveShaper();this.Xc=new Float32Array(65536);this.yf(b,d);this.mc.curve=this.Xc;this.l.connect(this.ic);this.l.connect(this.b);this.ic.connect(this.mc);this.mc.connect(this.hc);
this.hc.connect(this.c)}f(){this.l.disconnect();this.ic.disconnect();this.mc.disconnect();this.hc.disconnect();this.c.disconnect();this.b.disconnect();super.f()}ug(a,b){.01>a&&(a=.01);this.ic.gain.value=a;this.hc.gain.value=Math.pow(1/a,.6)*b}yf(a,b){for(let d=0;32768>d;++d){let h=d/32768;h=this.Ig(h,a,b);this.Xc[32768+d]=h;this.Xc[32768-d-1]=-h}}Ig(a,b,d){d=1.05*d*b-b;const h=0>a?-a:a;return(h<b?h:b+d*self.ea.Yg(h-b,1/d))*(0>a?-1:1)}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();
this.b.connect(a)}O(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.c.gain,b,d,h),this.m(this.b.gain,1-b,d,h)}}};self.ve=class extends f{constructor(a,b,d,h,n,q){super(a);this.P="compressor";this.g=[b,d,h,n,q];this.h=this.a.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=h;this.h.attack.value=n;this.h.release.value=q}f(){this.h.disconnect();super.f()}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(){}};
self.ue=class extends f{constructor(a,b,d){super(a);this.P="analyser";this.g=[b,d];this.h=this.a.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.$d=new Float32Array(this.h.frequencyBinCount);this.ne=new Uint8Array(b);this.le=this.Na=0;this.j.ff(this)}f(){this.j.ng(this);this.h.disconnect();super.f()}Ea(){this.h.getFloatFrequencyData(this.$d);this.h.getByteTimeDomainData(this.ne);const a=this.h.fftSize;let b=this.Na=0;for(var d=0;d<a;++d){let h=(this.ne[d]-128)/128;0>h&&(h=-h);
this.Na<h&&(this.Na=h);b+=h*h}d=self.ea.Ve;this.Na=d(this.Na);this.le=d(Math.sqrt(b/a))}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(){}Oe(){return{tag:this.Z,index:this.ce,peak:this.Na,rms:this.le,binCount:this.h.frequencyBinCount,freqBins:this.$d}}}}"use strict";function fa(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>w(f,"sw-message",a.data))}
function ha(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(f):screen.webkitLockOrientation?a=screen.webkitLockOrientation(f):screen.mozLockOrientation?a=screen.mozLockOrientation(f):screen.msLockOrientation&&(a=screen.msLockOrientation(f));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.wa.Ab(class extends self.Ua{constructor(f){super(f,"browser");this.s="";L(this,[["get-initial-state",a=>{this.s=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
fa(this)],["alert",a=>this.Ic(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Oc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ha(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,
"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.oh||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.s||"macos-wkwebview"===this.s)self.wa.Ob(!0),this.u.Sc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===
a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.s||"macos-wkwebview"===this.s?(self.wa.Ob(!1),this.u.Sc({type:"set-fullscreen",
fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{w(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{w(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{w(this,"hashchange",
{location:location.toString()})});document.addEventListener("backbutton",()=>{w(this,"backbutton")})}Ic(f){alert(f.message)}Oc(f){f=f.isFocus;if("nwjs"===this.s){const a="nwjs"===this.s?nw.Window.get():null;f?a.focus():a.blur()}else f?window.focus():window.blur()}});
